{
 "title": "[DEALLab] pod disk usage",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "pod1 디스크 용량",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod1-pvc\"}) / (1024*1024*1024)",
     "legendFormat": "pod1 디스크 용량"
    },
    {
     "expr": "max((kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod1-pvc\"}  - kubelet_volume_stats_available_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod1-pvc\"})) / (1024*1024*1024)",
     "legendFormat": " pod1 디스크 사용 용량"
    }
   ]
  },
  {
   "title": "pod1 전체용량 ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod1-pvc\"})  / 1024 / 1024 / 1024\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pod2 디스크 용량",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}) / (1024*1024*1024)",
     "legendFormat": "pod1 디스크 용량"
    },
    {
     "expr": "max((kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}  - kubelet_volume_stats_available_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})) / (1024*1024*1024)",
     "legendFormat": " pod1 디스크 사용 용량"
    }
   ]
  },
  {
   "title": "pod2 전체용량 ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})  / 1024 / 1024 / 1024\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pod3 디스크 용량",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}) / (1024*1024*1024)",
     "legendFormat": "pod1 디스크 용량"
    },
    {
     "expr": "max((kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}  - kubelet_volume_stats_available_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})) / (1024*1024*1024)",
     "legendFormat": " pod1 디스크 사용 용량"
    }
   ]
  },
  {
   "title": "pod2 전체용량 ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})  / 1024 / 1024 / 1024\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pod4 디스크 용량",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}) / (1024*1024*1024)",
     "legendFormat": "pod1 디스크 용량"
    },
    {
     "expr": "max((kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}  - kubelet_volume_stats_available_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})) / (1024*1024*1024)",
     "legendFormat": " pod1 디스크 사용 용량"
    }
   ]
  },
  {
   "title": "pod2 전체용량 ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})  / 1024 / 1024 / 1024\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pod1 사용용량 ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod1-pvc\"}  - kubelet_volume_stats_available_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod1-pvc\"})) / (1024*1024*1024)"
    }
   ]
  },
  {
   "title": "pod2 사용용량 ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}  - kubelet_volume_stats_available_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})) / (1024*1024*1024)"
    }
   ]
  },
  {
   "title": "pod2 사용용량 ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}  - kubelet_volume_stats_available_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})) / (1024*1024*1024)"
    }
   ]
  },
  {
   "title": "pod2 사용용량 ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}  - kubelet_volume_stats_available_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})) / (1024*1024*1024)"
    }
   ]
  },
  {
   "title": "pi1 사용용량 (mounted)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mount_storage_used_byte{target=\"pi1\"}/1024/1024/1024"
    }
   ]
  },
  {
   "title": "pi2 사용용량 (mounted)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mount_storage_used_byte{target=\"pi2\"}/1024/1024/1024"
    }
   ]
  },
  {
   "title": "pi2 사용용량 (mounted)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mount_storage_used_byte{target=\"pi2\"}/1024/1024/1024"
    }
   ]
  },
  {
   "title": "pi2 사용용량 (mounted)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mount_storage_used_byte{target=\"pi2\"}/1024/1024/1024"
    }
   ]
  },
  {
   "title": "pod5 디스크 용량",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}) / (1024*1024*1024)",
     "legendFormat": "pod1 디스크 용량"
    },
    {
     "expr": "max((kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}  - kubelet_volume_stats_available_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})) / (1024*1024*1024)",
     "legendFormat": " pod1 디스크 사용 용량"
    }
   ]
  },
  {
   "title": "pod2 전체용량 ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})  / 1024 / 1024 / 1024\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pod6 디스크 용량",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}) / (1024*1024*1024)",
     "legendFormat": "pod1 디스크 용량"
    },
    {
     "expr": "max((kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}  - kubelet_volume_stats_available_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})) / (1024*1024*1024)",
     "legendFormat": " pod1 디스크 사용 용량"
    }
   ]
  },
  {
   "title": "pod2 전체용량 ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})  / 1024 / 1024 / 1024\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pod7 디스크 용량",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}) / (1024*1024*1024)",
     "legendFormat": "pod1 디스크 용량"
    },
    {
     "expr": "max((kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}  - kubelet_volume_stats_available_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})) / (1024*1024*1024)",
     "legendFormat": " pod1 디스크 사용 용량"
    }
   ]
  },
  {
   "title": "pod2 전체용량 ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})  / 1024 / 1024 / 1024\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pod8 디스크 용량",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}) / (1024*1024*1024)",
     "legendFormat": "pod1 디스크 용량"
    },
    {
     "expr": "max((kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}  - kubelet_volume_stats_available_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})) / (1024*1024*1024)",
     "legendFormat": " pod1 디스크 사용 용량"
    }
   ]
  },
  {
   "title": "pod2 전체용량 ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})  / 1024 / 1024 / 1024\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pod2 사용용량 ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}  - kubelet_volume_stats_available_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})) / (1024*1024*1024)"
    }
   ]
  },
  {
   "title": "pod2 사용용량 ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}  - kubelet_volume_stats_available_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})) / (1024*1024*1024)"
    }
   ]
  },
  {
   "title": "pod2 사용용량 ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}  - kubelet_volume_stats_available_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})) / (1024*1024*1024)"
    }
   ]
  },
  {
   "title": "pod2 사용용량 ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}  - kubelet_volume_stats_available_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})) / (1024*1024*1024)"
    }
   ]
  },
  {
   "title": "pi2 사용용량 (mounted)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mount_storage_used_byte{target=\"pi2\"}/1024/1024/1024"
    }
   ]
  },
  {
   "title": "pi2 사용용량 (mounted)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mount_storage_used_byte{target=\"pi2\"}/1024/1024/1024"
    }
   ]
  },
  {
   "title": "pi2 사용용량 (mounted)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mount_storage_used_byte{target=\"pi2\"}/1024/1024/1024"
    }
   ]
  },
  {
   "title": "pi2 사용용량 (mounted)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mount_storage_used_byte{target=\"pi2\"}/1024/1024/1024"
    }
   ]
  },
  {
   "title": "pod2 디스크 용량",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}) / (1024*1024*1024)",
     "legendFormat": "pod1 디스크 용량"
    },
    {
     "expr": "max((kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}  - kubelet_volume_stats_available_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})) / (1024*1024*1024)",
     "legendFormat": " pod1 디스크 사용 용량"
    }
   ]
  },
  {
   "title": "pod2 전체용량 ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})  / 1024 / 1024 / 1024\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pod2 디스크 용량",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}) / (1024*1024*1024)",
     "legendFormat": "pod1 디스크 용량"
    },
    {
     "expr": "max((kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}  - kubelet_volume_stats_available_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})) / (1024*1024*1024)",
     "legendFormat": " pod1 디스크 사용 용량"
    }
   ]
  },
  {
   "title": "pod2 전체용량 ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})  / 1024 / 1024 / 1024\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pod2 디스크 용량",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}) / (1024*1024*1024)",
     "legendFormat": "pod1 디스크 용량"
    },
    {
     "expr": "max((kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}  - kubelet_volume_stats_available_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})) / (1024*1024*1024)",
     "legendFormat": " pod1 디스크 사용 용량"
    }
   ]
  },
  {
   "title": "pod2 전체용량 ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})  / 1024 / 1024 / 1024\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pod2 디스크 용량",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}) / (1024*1024*1024)",
     "legendFormat": "pod1 디스크 용량"
    },
    {
     "expr": "max((kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}  - kubelet_volume_stats_available_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})) / (1024*1024*1024)",
     "legendFormat": " pod1 디스크 사용 용량"
    }
   ]
  },
  {
   "title": "pod2 전체용량 ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})  / 1024 / 1024 / 1024\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pod2 사용용량 ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}  - kubelet_volume_stats_available_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})) / (1024*1024*1024)"
    }
   ]
  },
  {
   "title": "pod2 사용용량 ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}  - kubelet_volume_stats_available_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})) / (1024*1024*1024)"
    }
   ]
  },
  {
   "title": "pod2 사용용량 ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}  - kubelet_volume_stats_available_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})) / (1024*1024*1024)"
    }
   ]
  },
  {
   "title": "pod2 사용용량 ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}  - kubelet_volume_stats_available_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})) / (1024*1024*1024)"
    }
   ]
  },
  {
   "title": "pi2 사용용량 (mounted)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mount_storage_used_byte{target=\"pi2\"}/1024/1024/1024"
    }
   ]
  },
  {
   "title": "pi2 사용용량 (mounted)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mount_storage_used_byte{target=\"pi2\"}/1024/1024/1024"
    }
   ]
  },
  {
   "title": "pi2 사용용량 (mounted)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mount_storage_used_byte{target=\"pi2\"}/1024/1024/1024"
    }
   ]
  },
  {
   "title": "pi2 사용용량 (mounted)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mount_storage_used_byte{target=\"pi2\"}/1024/1024/1024"
    }
   ]
  },
  {
   "title": "pod2 디스크 용량",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}) / (1024*1024*1024)",
     "legendFormat": "pod1 디스크 용량"
    },
    {
     "expr": "max((kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}  - kubelet_volume_stats_available_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})) / (1024*1024*1024)",
     "legendFormat": " pod1 디스크 사용 용량"
    }
   ]
  },
  {
   "title": "pod2 전체용량 ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})  / 1024 / 1024 / 1024\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pod2 디스크 용량",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}) / (1024*1024*1024)",
     "legendFormat": "pod1 디스크 용량"
    },
    {
     "expr": "max((kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}  - kubelet_volume_stats_available_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})) / (1024*1024*1024)",
     "legendFormat": " pod1 디스크 사용 용량"
    }
   ]
  },
  {
   "title": "pod2 전체용량 ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})  / 1024 / 1024 / 1024\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pod2 디스크 용량",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}) / (1024*1024*1024)",
     "legendFormat": "pod1 디스크 용량"
    },
    {
     "expr": "max((kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}  - kubelet_volume_stats_available_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})) / (1024*1024*1024)",
     "legendFormat": " pod1 디스크 사용 용량"
    }
   ]
  },
  {
   "title": "pod2 전체용량 ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})  / 1024 / 1024 / 1024\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pod2 디스크 용량",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 18, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}) / (1024*1024*1024)",
     "legendFormat": "pod1 디스크 용량"
    },
    {
     "expr": "max((kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}  - kubelet_volume_stats_available_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})) / (1024*1024*1024)",
     "legendFormat": " pod1 디스크 사용 용량"
    }
   ]
  },
  {
   "title": "pod2 전체용량 ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})  / 1024 / 1024 / 1024\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pod2 사용용량 ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}  - kubelet_volume_stats_available_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})) / (1024*1024*1024)"
    }
   ]
  },
  {
   "title": "pod2 사용용량 ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}  - kubelet_volume_stats_available_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})) / (1024*1024*1024)"
    }
   ]
  },
  {
   "title": "pod2 사용용량 ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}  - kubelet_volume_stats_available_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})) / (1024*1024*1024)"
    }
   ]
  },
  {
   "title": "pod2 사용용량 ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}  - kubelet_volume_stats_available_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})) / (1024*1024*1024)"
    }
   ]
  },
  {
   "title": "pi2 사용용량 (mounted)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mount_storage_used_byte{target=\"pi2\"}/1024/1024/1024"
    }
   ]
  },
  {
   "title": "pi2 사용용량 (mounted)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mount_storage_used_byte{target=\"pi2\"}/1024/1024/1024"
    }
   ]
  },
  {
   "title": "pi2 사용용량 (mounted)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mount_storage_used_byte{target=\"pi2\"}/1024/1024/1024"
    }
   ]
  },
  {
   "title": "pi2 사용용량 (mounted)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mount_storage_used_byte{target=\"pi2\"}/1024/1024/1024"
    }
   ]
  },
  {
   "title": "pod2 디스크 용량",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}) / (1024*1024*1024)",
     "legendFormat": "pod1 디스크 용량"
    },
    {
     "expr": "max((kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}  - kubelet_volume_stats_available_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})) / (1024*1024*1024)",
     "legendFormat": " pod1 디스크 사용 용량"
    }
   ]
  },
  {
   "title": "pod2 전체용량 ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})  / 1024 / 1024 / 1024\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pod2 디스크 용량",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 6, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}) / (1024*1024*1024)",
     "legendFormat": "pod1 디스크 용량"
    },
    {
     "expr": "max((kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}  - kubelet_volume_stats_available_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})) / (1024*1024*1024)",
     "legendFormat": " pod1 디스크 사용 용량"
    }
   ]
  },
  {
   "title": "pod2 전체용량 ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})  / 1024 / 1024 / 1024\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pod2 디스크 용량",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}) / (1024*1024*1024)",
     "legendFormat": "pod1 디스크 용량"
    },
    {
     "expr": "max((kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}  - kubelet_volume_stats_available_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})) / (1024*1024*1024)",
     "legendFormat": " pod1 디스크 사용 용량"
    }
   ]
  },
  {
   "title": "pod2 전체용량 ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})  / 1024 / 1024 / 1024\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pod2 디스크 용량",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 18, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}) / (1024*1024*1024)",
     "legendFormat": "pod1 디스크 용량"
    },
    {
     "expr": "max((kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}  - kubelet_volume_stats_available_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})) / (1024*1024*1024)",
     "legendFormat": " pod1 디스크 사용 용량"
    }
   ]
  },
  {
   "title": "pod2 전체용량 ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})  / 1024 / 1024 / 1024\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pod2 사용용량 ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}  - kubelet_volume_stats_available_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})) / (1024*1024*1024)"
    }
   ]
  },
  {
   "title": "pod2 사용용량 ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}  - kubelet_volume_stats_available_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})) / (1024*1024*1024)"
    }
   ]
  },
  {
   "title": "pod2 사용용량 ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}  - kubelet_volume_stats_available_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})) / (1024*1024*1024)"
    }
   ]
  },
  {
   "title": "pod2 사용용량 ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((kubelet_volume_stats_capacity_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"}  - kubelet_volume_stats_available_bytes{namespace=\"ksv\" , persistentvolumeclaim=\"pod2-pvc\"})) / (1024*1024*1024)"
    }
   ]
  },
  {
   "title": "pi2 사용용량 (mounted)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mount_storage_used_byte{target=\"pi2\"}/1024/1024/1024"
    }
   ]
  },
  {
   "title": "pi2 사용용량 (mounted)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mount_storage_used_byte{target=\"pi2\"}/1024/1024/1024"
    }
   ]
  },
  {
   "title": "pi2 사용용량 (mounted)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mount_storage_used_byte{target=\"pi2\"}/1024/1024/1024"
    }
   ]
  },
  {
   "title": "pi2 사용용량 (mounted)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mount_storage_used_byte{target=\"pi2\"}/1024/1024/1024"
    }
   ]
  }
 ]
}