kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-pvc
 # namespace: default
  annotations:
    resize.topolvm.io/threshold: 20%
    resize.topolvm.io/increase: 5Gi
    resize.topolvm.io/inodes-threshold: 0%
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 3Gi
    limits:
      storage: 20Gi
  storageClassName: rook-cephfs
